# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondchances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_string',
            field=models.CharField(max_length=54, null=True),
        ),
    ]
